# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ../users/nrd ];

  boot.initrd.availableKernelModules =
    [ "ata_piix" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/253e56ea-78a8-41bf-b978-93ddd4737c7a";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3D00-98C1";
    fsType = "vfat";
  };

  networking.useDHCP = false;
  networking.interfaces.ens3.useDHCP = true;

  swapDevices = [ ];

  services.openssh.enable = true;

  nix.maxJobs = lib.mkDefault 6;
}
